ServerEvents.recipes(event=>{
    event.recipes.mekanism.metallurgic_infusing('ae2:calculation_processor_press','#ae2:all_certus_quartz','80x mekanism:tin')
    event.recipes.mekanism.metallurgic_infusing('ae2:engineering_processor_press','#ae2:all_certus_quartz','80x mekanism:diamond')
    event.recipes.mekanism.metallurgic_infusing('ae2:logic_processor_press','#ae2:all_certus_quartz','80x mekanism:gold')
    event.recipes.mekanism.metallurgic_infusing('ae2:silicon_press','#ae2:all_certus_quartz','80x mekanism:carbon')
    event.recipes.mekanism.metallurgic_infusing('ae2:printed_calculation_processor','#forge:raw_mutton','10x farmindustry:certus_quartz')
    event.recipes.mekanism.metallurgic_infusing('ae2:printed_engineering_processor','#forge:raw_beef','10x mekanism:diamond')
    event.recipes.mekanism.metallurgic_infusing('ae2:printed_logic_processor','#forge:raw_pork','10x mekanism:diamond')
    event.recipes.mekanism.metallurgic_infusing('ae2:printed_silicon','#forge:raw_chicken','10x farmindustry:silicon')
    event.recipes.mekanism.metallurgic_infusing('farmindustry:infused_printed_silicon','ae2:printed_silicon','40x mekanism:redstone')
    event.recipes.mekanism.metallurgic_infusing('ae2:sky_dust','minecraft:rabbit_foot','10x mekanism:carbon')
    event.recipes.mekanism.metallurgic_infusing('megacells:sky_steel_ingot','8x ae2:sky_dust','80x farmindustry:certus_quartz')
    event.recipes.mekanism.combining('ae2:calculation_processor','ae2:printed_calculation_processor','farmindustry:infused_printed_silicon')
    event.recipes.mekanism.combining('ae2:engineering_processor','ae2:printed_engineering_processor','farmindustry:infused_printed_silicon')
    event.recipes.mekanism.combining('ae2:logic_processor','ae2:printed_logic_processor','farmindustry:infused_printed_silicon')
    event.recipes.mekanism.combining('megacells:accumulation_processor','megacells:printed_accumulation_processor','farmindustry:infused_printed_silicon')
    event.recipes.mekanism.enriching('farmindustry:enriched_silicon','#forge:silicon')
    event.recipes.mekanism.enriching('farmindustry:enriched_quartz','#ae2:all_certus_quartz')
    event.recipes.mekanism.metallurgic_infusing('ae2:charged_certus_quartz_crystal','ae2:certus_quartz_crystal','80x mekanism:redstone')
    event.recipes.mekanism.combining('ae2:fluix_crystal','ae2:charged_certus_quartz_crystal','#forge:gems/quartz')
    event.recipes.mekanism.combining('ae2:silicon','minecraft:leather','#minecraft:wool')
    event.recipes.mekanism.combining('2x ae2:certus_quartz_crystal','#forge:gems/quartz','minecraft:rabbit')
    event.recipes.mekanism.combining('ae2:matter_ball','16x #minecraft:fishes','#forge:silicon')
    event.recipes.mekanism.combining('ae2:singularity','2x #farmindustry:compress/triple','ae2:cell_component_64k')
    event.recipes.mekanism.combining('megacells:printed_accumulation_processor','ae2:engineering_processor','#forge:ingots/sky_steel')
    event.recipes.mekanism.crushing('ae2:ender_dust','#forge:ender_pearls')
    
    event.remove({id:"ae2:network/blocks/inscribers"})
    event.custom({type:'mekanism:infusion_conversion',input:{'ingredient':{'tag':'forge:silicon'}},output:{'infuse_type':'farmindustry:silicon','amount':10}})
    event.custom({type:'mekanism:infusion_conversion',input:{'ingredient':{'tag':'ae2:all_certus_quartz'}},output:{'infuse_type':'farmindustry:certus_quartz','amount':10}})
    event.custom({type:'mekanism:infusion_conversion',input:{'ingredient':{'item':'farmindustry:enriched_silicon'}},output:{'infuse_type':'farmindustry:silicon','amount':80}})
    event.custom({type:'mekanism:infusion_conversion',input:{'ingredient':{'item':'farmindustry:enriched_quartz'}},output:{'infuse_type':'farmindustry:certus_quartz','amount':80}})
})