ServerEvents.recipes(event => {
    event.recipes.custommachinery.custom_machine("autofarms:compact_fission", 1)
        .requireItem('minecraft:cobblestone',"cata").chance(0)
        .requireFluid("minecraft:water 20000000")
        .requireGas("mekanism:fissile_fuel 1000", "gas1")
        .produceGas("mekanism:nuclear_waste 1000", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_fission", 1)
        .requireItem('farmindustry:gluttony_cake',"cata").chance(0)
        .requireFluid("minecraft:water 80000000")
        .requireGas("mekanism:fissile_fuel 2000", "gas1")
        .produceGas("mekanism:nuclear_waste 2000", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_fission", 1)
        .requireItem('mekanism:qio_drive_time_dilating',"cata").chance(0)
        .requireFluid("minecraft:water 100000000")
        .requireGas("mekanism:fissile_fuel 5000", "gas1")
        .produceGas("mekanism:nuclear_waste 5000", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_fission", 1)
        .requireItem('farmindustry:ultimate_valine_3g',"cata").chance(0)
        .requireFluid("minecraft:water 500000000")
        .requireGas("mekanism:fissile_fuel 50000", "gas1")
        .produceGas("mekanism:nuclear_waste 50000", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_fission", 1)
        .requireItem('farmindustry:ultimate_valine_3g_ingot',"cata").chance(0)
        .requireFluid("minecraft:water 1000000000")
        .requireGas("mekanism:fissile_fuel 100000", "gas1")
        .produceGas("mekanism:nuclear_waste 100000", "gas2")
        .resetOnError()
    })
    ServerEvents.recipes(event=>{
        event.recipes.mekanism.combining(Item.of('custommachinery:custom_machine_item','{machine:"autofarms:compact_fission"}'),'64x mekanismgenerators:fission_reactor_casing','farmindustry:living_bowl')
})