ServerEvents.recipes(event => {
    event.recipes.custommachinery.custom_machine("autofarms:compact_sps", 1)
        .requireItem("minecraft:cobblestone",1).chance(0)
        .requireEnergyPerTick(40000000)
        .requireGas("mekanism:polonium 2000", "gas1")
        .produceGas("mekanism:antimatter 2", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_sps", 1)
        .requireItem('farmindustry:abyss_bowl',"cata").chance(0)
        .requireEnergyPerTick(80000000)
        .requireGas("mekanism:polonium 4000", "gas1")
        .produceGas("mekanism:antimatter 10", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_sps", 1)
        .requireItem('farmindustry:living_bowl',"cata").chance(0)
        .requireEnergyPerTick(400000000)
        .requireGas("mekanism:polonium 5000", "gas1")
        .produceGas("mekanism:antimatter 40", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_sps", 1)
        .requireItem('farmindustry:devil_valine_3g',"cata").chance(0)
        .requireEnergyPerTick(800000000)
        .requireGas("mekanism:polonium 10000", "gas1")
        .produceGas("mekanism:antimatter 200", "gas2")
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:compact_sps", 1)
        .requireItem('farmindustry:devil_valine_3g_ingot',"cata").chance(0)
        .requireEnergyPerTick(1000000000)
        .requireGas("mekanism:polonium 10000", "gas1")
        .produceGas("mekanism:antimatter 1000", "gas2")
        .resetOnError()
    })
    ServerEvents.recipes(event=>{
        event.recipes.mekanism.combining(Item.of('custommachinery:custom_machine_item','{machine:"autofarms:compact_sps"}'),'64x mekanism:sps_casing','farmindustry:living_bowl')
})