ServerEvents.recipes(event => {
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer", 1)
        .requireItem(Item.of('minecraft:kelp',20))
        .requireItem(Item.of('farmersdelight:rice_panicle',20))
        .requireFluid(Fluid.of('minecraft:water',10000))
        .requireEnergyPerTick(2000)
        .produceFluid(Fluid.of('farmindustry:liquid_fertilizer_tier1',5000))
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer", 1)
        .requireItem(Item.of('farmindustry:melon_ingot_base',40))
        .requireItemTag('#forge:dusts/iron',40)
        .requireFluid(Fluid.of('farmindustry:liquid_fertilizer_tier1',10000))
        .requireEnergyPerTick(32000)
        .produceFluid(Fluid.of('farmindustry:liquid_fertilizer_tier2',5000))
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer", 1)
        .requireItem(Item.of('farmersdelight:shepherds_pie_block',60))
        .requireItem(Item.of('minecraft:cake',60))
        .requireFluid(Fluid.of('farmindustry:liquid_fertilizer_tier2',10000))
        .requireFluid(Fluid.of('minecraft:milk',80000))
        .requireEnergyPerTick(640000)
        .produceFluid(Fluid.of('farmindustry:liquid_fertilizer_tier3',5000))
        .resetOnError()
        event.recipes.custommachinery.custom_machine("autofarms:super_mixer", 1)
        .requireItem(Item.of('farmindustry:many_kinds_of_bread',10))
        .requireItem(Item.of('farmindustry:sea_food_rice',10))
        .requireFluid(Fluid.of('farmindustry:liquid_fertilizer_tier3',10000))
        .requireFluid(Fluid.of('farmindustry:hot_chocolate',80000))
        .requireEnergyPerTick(80000)
        .produceFluid(Fluid.of('farmindustry:liquid_fertilizer_tier4',5000))
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer", 1)
        .requireItem(Item.of('farmindustry:eatable_server',10))
        .requireItem(Item.of('farmindustry:living_bowl',10))
        .requireFluid(Fluid.of('farmindustry:liquid_fertilizer_tier4',10000))
        .requireFluid(Fluid.of('mekanism:nutritional_paste',160000))
        .requireEnergyPerTick(160000)
        .produceFluid(Fluid.of('farmindustry:liquid_fertilizer_tier5',5000))
        .resetOnError()
        event.recipes.custommachinery.custom_machine("autofarms:super_mixer", 1)
        .requireItem(Item.of('farmindustry:ultimate_valine_3g_ingot',60))
        .requireItem(Item.of('farmindustry:devil_valine_3g_ingot',60))
        .requireFluid(Fluid.of('farmindustry:liquid_fertilizer_tier5',10000))
        .requireFluid(Fluid.of('mekanismgenerators:fusion_fuel',160000))
        .requireEnergyPerTick(160000)
        .produceFluid(Fluid.of('farmindustry:liquid_fertilizer_tier6',5000))
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer",1)
        .requireEnergyPerTick(20)
        .requireItem(Item.of('20x minecraft:beef'))
        .produceFluid(Fluid.of('minecraft:milk',10000))
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer",1)
        .requireEnergyPerTick(2000)
        .requireItem(Item.of('minecraft:cocoa_beans',40))
        .requireFluid(Fluid.of('minecraft:milk',10000))
        .produceFluid(Fluid.of('farmindustry:liquid_chocolate',10000))
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer",1)
        .requireEnergyPerTick(2000)
        .requireItem(Item.of('40x minecraft:apple'))
        .requireFluid(Fluid.of('minecraft:water',10000))
        .produceFluid(Fluid.of('farmindustry:apple_juice',10000))
        .resetOnError()
    event.recipes.custommachinery.custom_machine("autofarms:super_mixer",1)
        .requireEnergyPerTick(2000)
        .requireFluid(Fluid.of('farmindustry:hot_chocolate',10000))
        .requireFluidTag('#minecraft:water',10000)
        .produceItem('10x minecraft:obsidian')
        .resetOnError()
})
ServerEvents.recipes(event=>{
    event.shaped(Item.of('custommachinery:custom_machine_item','{machine:"autofarms:super_mixer"}'),
[
  'BCB',
  'DAD',
  'BCB'
],
{
  A:'mekanism:ultimate_fluid_tank',
  B:'farmindustry:ingot_steel_single_compressed',
  C:'farmindustry:basic_control_circuit_single_compressed',
  D:'farmindustry:alloy_infused_single_compressed'
})
})