
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	enrichmentChamber = "200000"
	#Base energy storage (Joules).
	osmiumCompressor = "800000"
	#Base energy storage (Joules).
	combiner = "400000"
	#Base energy storage (Joules).
	crusher = "200000"
	#Base energy storage (Joules).
	metallurgicInfuser = "200000"
	#Base energy storage (Joules).
	purificationChamber = "800000"
	#Base energy storage (Joules).
	energizedSmelter = "200000"
	#Base energy storage (Joules).
	digitalMiner = "500000"
	#Base energy storage (Joules).
	electricPump = "400000"
	#Base energy storage (Joules).
	chargePad = "2048000"
	#Base energy storage (Joules).
	rotaryCondensentrator = "200000"
	#Base energy storage (Joules).
	oxidationChamber = "800000"
	#Base energy storage (Joules).
	chemicalInfuser = "800000"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "1600000"
	#Base energy storage (Joules).
	electrolyticSeparator = "1600000"
	#Base energy storage (Joules).
	precisionSawmill = "200000"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "1600000"
	#Base energy storage (Joules).
	chemicalWasher = "800000"
	#Base energy storage (Joules).
	chemicalCrystallizer = "1600000"
	#Base energy storage (Joules).
	seismicVibrator = "200000"
	#Base energy storage (Joules).
	pressurizedReactionBase = "20000"
	#Base energy storage (Joules).
	fluidicPlenisher = "400000"
	#Base energy storage (Joules).
	laser = "2000000"
	#Base energy storage (Joules).
	laserAmplifier = "5000000000"
	#Base energy storage (Joules).
	laserTractorBeam = "5000000000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "400000"
	#Base energy storage (Joules).
	teleporter = "50000000"
	#Base energy storage (Joules).
	modificationStation = "40000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "800000"
	#Base energy storage (Joules).
	nutritionalLiquifier = "400000"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "10000000000"
	#Base energy storage (Joules).
	pigmentExtractor = "400000"
	#Base energy storage (Joules).
	pigmentMixer = "800000"
	#Base energy storage (Joules).
	paintingMachine = "400000"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "1000000000"
	#Base energy storage (Joules).
	dimensionalStabilizer = "400000"

